---
title: "Cake_ingredients"
output: html_notebook
---


```{r}

library(tidyverse)
library(dplyr)
library(stringr)
library(janitor)
library(here)

```

We have a clean data set now under clean folder so we can start analysing data now.


```{r}
# load data

cake_ingredients <- read_csv(here("clean_data/cake_ingredients_clean.csv"))

```

```{r}

 names(cake_ingredients)
```

Analysis

```{r}
# cake with most cocoa

cake_ingredients %>%
  filter(ingredient == "cocoa") %>%
  filter(quantity == max(quantity)) %>%
  select(cake)
 
  
  

```


```{r}

# Ingredients are used in sponge cake  

cake_ingredients %>%
  filter(cake == "sponge") %>%
  filter(measure == "cup") %>%
  summarise(total_cups = sum(quantity))
  
  

```


```{r}

# Ingredients are measured in teaspoons

cake_ingredients %>%
  filter(measure == "teaspoon") %>%
  summarise(num_measure_teaspoon = n_distinct(ingredient))
  
  

  
  
  
 

```


```{r}

# unique ingredients?

cake_ingredients %>%
  group_by(cake) %>%
  summarise(num_ingredients = n()) %>%
  filter(num_ingredients == max(num_ingredients))
  

  

```


```{r}
# ingredients are used only once

cake_ingredients %>%
  group_by(ingredient) %>%
  summarise(num_ingredients = n()) %>%
  filter(num_ingredients == min(num_ingredients)) %>%
  select(ingredient)


  


```



















