---
title: "Halloween candy"
output: html_notebook
---

# Task 4 - Halloween Candy Data

# The data is in clean formt now we can use it to ananlyse 


```{r}

library(tidyverse)
library(dplyr)
library(stringr)
library(readr)
library(here)

```



```{r}
# Load data from first csv file 

halloween_candies <- 
  read_csv(here("clean_data/halloween_candies.csv"), guess_max = 1000001)



```




1.4.2 Analysis questions

Q1

```{r}
# candy ratings given across the three years

halloween_candies %>%
  drop_na(ratings)%>%
  summarise(candy_ratings = n())
  
  
```


Q2

```{r}
# average age of people who are going out trick or treating and the average age of people 3. not going trick or treating?

halloween_candies %>%
   group_by(going_out) %>%
   summarise(avg_age = mean(age, na.rm = TRUE))



```

Q3



```{r}
# candy bar revived the most of these ratings each of joy, despair and meh,

  
halloween_candies %>%
  drop_na(ratings) %>%
  group_by(ratings, candies) %>%
  summarise(candy_ratings = n()) %>%
  filter(candy_ratings == max(candy_ratings))
  

```


Q4

```{r}
#  people rated Starburst as despair

halloween_candies %>%
  drop_na(ratings) %>%
  group_by(candies, ratings) %>%
  filter(candies == 'starburst' & ratings == 'despair') %>%
  summarise(starburst_ratings = n())
  
  

```

For the next two questions, count despair as -1, joy as +1 and meh as 0.

```{r}
halloween_candies <-
  halloween_candies %>%
  mutate(ratings_numeric = recode(ratings, joy = 1, despair = -1, meh = 0))

```


Q5

```{r}
# most popular candy bar by this rating system for each gender in the dataset?

halloween_candies %>%
  group_by(gender, candies) %>%
  summarise(avg_rating = mean(ratings_numeric, na.rm = TRUE)) %>%
  filter(avg_rating == max(avg_rating))



```

Q6

```{r}

# most popular candy bar in each year

halloween_candies %>%
group_by(year, candies) %>%
summarise(avg_rating = mean(ratings_numeric, na.rm = TRUE)) %>%
filter(avg_rating == max(avg_rating))
 



```

Q7 

```{r}
# most popular candy bar by this rating for people in US, Canada, UK and all other countries

halloween_candies %>%
mutate(country = if_else(country %in% c("usa", "canada", "uk"), country, "other")) %>%
filter(year != 2015) %>%
group_by(country, candies) %>%
summarise(avg_rating = mean(ratings_numeric, na.rm = TRUE)) %>%
filter(avg_rating == max(avg_rating))


```


























